/*An M query for Strike Reports Info in the Curated Data group of the Strike Reports dataflow.*/
let
  Source = #"Strike Reports",
  #"Removed other columns" = Table.SelectColumns(Source, {"INCIDENT_DATE", "TIME_OF_DAY", "AIRPORT_ID", "AIRPORT", "LATITUDE", "LONGITUDE", "RUNWAY", "STATE", "FAAREGION", "OPID", "OPERATOR", "FLT", "AIRCRAFT", "AMA", "AMO", "EMA", "EMO", "AC_CLASS", "AC_MASS", "TYPE_ENG", "NUM_ENGS", "ENG_1_POS", "ENG_2_POS", "ENG_3_POS", "ENG_4_POS", "PHASE_OF_FLIGHT", "HEIGHT", "SPEED", "DISTANCE", "SKY", "PRECIPITATION", "AOS", "COST_REPAIRS", "COST_OTHER", "COST_REPAIRS_INFL_ADJ", "COST_OTHER_INFL_ADJ", "INGESTED_OTHER", "INDICATED_DAMAGE", "DAMAGE_LEVEL", "STR_RAD", "DAM_RAD", "STR_WINDSHLD", "DAM_WINDSHLD", "STR_NOSE", "DAM_NOSE", "STR_ENG1", "DAM_ENG1", "ING_ENG1", "STR_ENG2", "DAM_ENG2", "ING_ENG2", "STR_ENG3", "DAM_ENG3", "ING_ENG3", "STR_ENG4", "DAM_ENG4", "ING_ENG4", "STR_PROP", "DAM_PROP", "STR_WING_ROT", "DAM_WING_ROT", "STR_FUSE", "DAM_FUSE", "STR_LG", "DAM_LG", "STR_TAIL", "DAM_TAIL", "STR_LGHTS", "DAM_LGHTS", "STR_OTHER", "DAM_OTHER", "EFFECT", "SPECIES_ID", "SPECIES", "REMARKS", "WARNED", "NUM_SEEN", "NUM_STRUCK", "SIZE", "ENROUTE_STATE", "NR_INJURIES", "NR_FATALITIES"}),
  #"Changed column type" = Table.TransformColumnTypes(#"Removed other columns", {{"INCIDENT_DATE", type datetime}, {"TIME_OF_DAY", type text}, {"AIRPORT_ID", type text}, {"AIRPORT", type text}, {"RUNWAY", type text}, {"STATE", type text}, {"FAAREGION", type text}, {"OPID", type text}, {"OPERATOR", type text}, {"FLT", type text}, {"AIRCRAFT", type text}, {"AMA", type text}, {"AC_CLASS", type text}, {"AC_MASS", type text}, {"TYPE_ENG", type text}, {"NUM_ENGS", type text}, {"ENG_1_POS", type text}, {"ENG_2_POS", type text}, {"ENG_3_POS", type text}, {"ENG_4_POS", type text}, {"PHASE_OF_FLIGHT", type text}, {"HEIGHT", Int64.Type}, {"SPEED", Int64.Type}, {"SKY", type text}, {"PRECIPITATION", type text}, {"COST_REPAIRS", Currency.Type}, {"COST_OTHER", Currency.Type}, {"COST_REPAIRS_INFL_ADJ", Currency.Type}, {"COST_OTHER_INFL_ADJ", Currency.Type}, {"INGESTED_OTHER", Int64.Type}, {"INDICATED_DAMAGE", Int64.Type}, {"DAMAGE_LEVEL", type text}, {"STR_RAD", Int64.Type}, {"DAM_RAD", Int64.Type}, {"STR_WINDSHLD", Int64.Type}, {"DAM_WINDSHLD", Int64.Type}, {"STR_NOSE", Int64.Type}, {"DAM_NOSE", Int64.Type}, {"STR_ENG1", Int64.Type}, {"DAM_ENG1", Int64.Type}, {"ING_ENG1", Int64.Type}, {"STR_ENG2", Int64.Type}, {"DAM_ENG2", Int64.Type}, {"ING_ENG2", Int64.Type}, {"STR_ENG3", Int64.Type}, {"DAM_ENG3", Int64.Type}, {"ING_ENG3", Int64.Type}, {"STR_ENG4", Int64.Type}, {"DAM_ENG4", Int64.Type}, {"ING_ENG4", Int64.Type}, {"STR_PROP", Int64.Type}, {"DAM_PROP", Int64.Type}, {"STR_WING_ROT", Int64.Type}, {"DAM_WING_ROT", Int64.Type}, {"STR_FUSE", Int64.Type}, {"DAM_FUSE", Int64.Type}, {"STR_LG", Int64.Type}, {"DAM_LG", Int64.Type}, {"STR_TAIL", Int64.Type}, {"DAM_TAIL", Int64.Type}, {"STR_LGHTS", Int64.Type}, {"DAM_LGHTS", Int64.Type}, {"STR_OTHER", Int64.Type}, {"DAM_OTHER", Int64.Type}, {"EFFECT", type text}, {"SPECIES_ID", type text}, {"SPECIES", type text}, {"REMARKS", type text}, {"WARNED", type text}, {"NUM_SEEN", type text}, {"NUM_STRUCK", type text}, {"SIZE", type text}, {"ENROUTE_STATE", type text}, {"NR_INJURIES", type text}, {"NR_FATALITIES", type text}}),
  #"Changed column type 1" = Table.TransformColumnTypes(#"Changed column type", {{"INCIDENT_DATE", type date}}),
  #"Renamed columns" = Table.RenameColumns(#"Changed column type 1", {{"INCIDENT_DATE", "Incident Date"}, {"TIME_OF_DAY", "Time of Day"}, {"AIRPORT_ID", "Airport ID"}, {"AIRPORT", "Airport Name"}, {"STATE", "State"}, {"ENROUTE_STATE", "Enroute State"}, {"FAAREGION", "FAA Region"}, {"RUNWAY", "Runway"}, {"LATITUDE", "Latitude"}, {"LONGITUDE", "Longitude"}, {"OPID", "Operator ID"}, {"OPERATOR", "Operator"}, {"AIRCRAFT", "Aircraft"}, {"COST_OTHER_INFL_ADJ", "Other Costs Adjusted"}, {"DAMAGE_LEVEL", "Damage Level"}, {"EFFECT", "Effect on Flight"}, {"REMARKS", "Remarks"}, {"NR_INJURIES", "Number of Injuries"}, {"NR_FATALITIES", "Number of Fatalities"}, {"INGESTED_OTHER", "Ingested Other"}, {"INDICATED_DAMAGE", "Indicated Damage"}, {"STR_RAD", "Struck Random"}, {"DAM_RAD", "Damaged Random"}, {"STR_WINDSHLD", "Struck Windshield"}, {"DAM_WINDSHLD", "Damaged Windshield"}, {"STR_NOSE", "Struck Nose"}, {"DAM_NOSE", "Damaged Nose"}, {"AC_CLASS", "Aircraft Class Code"}, {"STR_ENG1", "Struck Engine 1"}, {"DAM_ENG1", "Damaged Engine 1"}, {"ING_ENG1", "Ingested Engine 1"}, {"STR_PROP", "Struck Propeller"}, {"AC_MASS", "Aircraft Mass Code"}, {"TYPE_ENG", "Engine Type Code"}, {"NUM_ENGS", "Number of Engines"}, {"ENG_1_POS", "Engine 1 Position Code"}, {"ENG_2_POS", "Engine 2 Position Code"}, {"ENG_3_POS", "Engine 3 Position Code"}, {"ENG_4_POS", "Engine 4 Position Code"}, {"SPECIES_ID", "Species ID"}, {"SPECIES", "Species"}, {"WARNED", "Warned"}, {"NUM_SEEN", "Number Seen"}, {"NUM_STRUCK", "Number Struck"}, {"SIZE", "Size"}, {"PHASE_OF_FLIGHT", "Phase of Flight"}, {"DAM_PROP", "Damaged Propeller"}, {"STR_ENG2", "Struck Engine 2"}, {"DAM_ENG2", "Damaged Engine 2"}, {"ING_ENG2", "Ingested Engine 2"}, {"STR_ENG3", "Struck Engine 3"}, {"DAM_ENG3", "Damaged Engine 3"}, {"ING_ENG3", "Ingested Engine 3"}, {"STR_LG", "Struck Landing Gear"}, {"DAM_LG", "Damaged Landing Gear"}, {"STR_TAIL", "Struck Tail"}, {"HEIGHT", "Height"}, {"SPEED", "Speed"}, {"DISTANCE", "Distance"}, {"SKY", "Sky"}, {"PRECIPITATION", "Precipitation"}, {"COST_REPAIRS", "Cost of Repairs"}, {"COST_OTHER", "Other Costs"}, {"DAM_TAIL", "Damaged Tail"}, {"STR_ENG4", "Struck Engine 4"}, {"DAM_ENG4", "Damaged Engine 4"}, {"ING_ENG4", "Ingested Engine 4"}, {"STR_LGHTS", "Struck Lights"}, {"DAM_LGHTS", "Damaged Lights"}, {"STR_OTHER", "Struck Other"}, {"DAM_OTHER", "Damaged Other"}, {"STR_WING_ROT", "Struck Wing or Rotor"}, {"DAM_WING_ROT", "Damaged Wing or Rotor"}, {"STR_FUSE", "Struck Fuselage"}, {"DAM_FUSE", "Damaged Fuselage"}, {"COST_REPAIRS_INFL_ADJ", "Cost of Repairs Adjusted"}}),
  #"Changed column type 2" = Table.TransformColumnTypes(#"Renamed columns", {{"Latitude", type number}, {"Longitude", type number}, {"Distance", Int64.Type}, {"AOS", Int64.Type}}),
  #"Replaced value" = Table.ReplaceValue(#"Changed column type 2", "", "blank", Replacer.ReplaceValue, {"Aircraft Class Code"}),
  #"Replaced value 1" = Table.ReplaceValue(#"Replaced value", "", "blank", Replacer.ReplaceValue, {"Engine 1 Position Code"}),
  #"Replaced value 2" = Table.ReplaceValue(#"Replaced value 1", "", "blank", Replacer.ReplaceValue, {"Engine 2 Position Code"}),
  #"Replaced value 3" = Table.ReplaceValue(#"Replaced value 2", "", "blank", Replacer.ReplaceValue, {"Engine 3 Position Code"}),
  #"Replaced value 4" = Table.ReplaceValue(#"Replaced value 3", "", "blank", Replacer.ReplaceValue, {"Engine 4 Position Code"}),
  #"Added custom" = Table.AddColumn(#"Replaced value 4", "Total Costs Adjusted", each if [Cost of Repairs Adjusted] = null then  [Other Costs Adjusted]
else if [Other Costs Adjusted] = null then [Cost of Repairs Adjusted] 
else [Cost of Repairs Adjusted] + [Other Costs Adjusted]),
  #"Replaced value 5" = Table.ReplaceValue(#"Added custom", null, 0, Replacer.ReplaceValue, {"Total Costs Adjusted"}),
  #"Changed column type 3" = Table.TransformColumnTypes(#"Replaced value 5", {{"Total Costs Adjusted", Currency.Type}}),
  #"Added custom 1" = Table.AddColumn(#"Changed column type 3", "Number of Engines Struck", each [Struck Engine 1] + [Struck Engine 2] + [Struck Engine 3] + [Struck Engine 4]),
  #"Added custom 2" = Table.AddColumn(#"Added custom 1", "Percentage of Engines Struck", each if [Number of Engines] = "NULL" then 0 
else Value.Divide([Number of Engines Struck],Number.From([Number of Engines]))),
  #"Replaced value 6" = Table.ReplaceValue(#"Added custom 2", null, 0, Replacer.ReplaceValue, {"Percentage of Engines Struck"}),
  #"Changed column type 4" = Table.TransformColumnTypes(#"Replaced value 6", {{"Percentage of Engines Struck", type number}, {"Number of Engines Struck", Int64.Type}}),
  #"Added custom 3" = Table.AddColumn(#"Changed column type 4", "Number of Engines Ingested", each [Ingested Engine 1] + [Ingested Engine 2] + [Ingested Engine 3] + [Ingested Engine 4]),
  #"Added custom 4" = Table.AddColumn(#"Added custom 3", "Percentage of Engines Ingested", each if [Number of Engines] = "NULL" then 0 
else Value.Divide([Number of Engines Ingested],Number.From([Number of Engines]))),
  #"Changed column type 5" = Table.TransformColumnTypes(#"Added custom 4", {{"Percentage of Engines Ingested", type number}, {"Number of Engines Ingested", Int64.Type}}),
  #"Replaced value 7" = Table.ReplaceValue(#"Changed column type 5", null, 0, Replacer.ReplaceValue, {"Percentage of Engines Ingested"}),
  #"Added custom 5" = Table.AddColumn(#"Replaced value 7", "Number of Engines Damaged", each [Damaged Engine 1] + [Damaged Engine 2] + [Damaged Engine 3] + [Damaged Engine 4]),
  #"Added custom 6" = Table.AddColumn(#"Added custom 5", "Perentage of Engines Damaged", each if [Number of Engines] = "NULL" then 0 
else Value.Divide([Number of Engines Damaged],Number.From([Number of Engines]))),
  #"Changed column type 6" = Table.TransformColumnTypes(#"Added custom 6", {{"Perentage of Engines Damaged", type number}, {"Number of Engines Damaged", Int64.Type}}),
  #"Replaced value 8" = Table.ReplaceValue(#"Changed column type 6", "", "blank", Replacer.ReplaceValue, {"Time of Day"}),
  #"Replaced value 9" = Table.ReplaceValue(#"Replaced value 8", "", "blank", Replacer.ReplaceValue, {"Sky"}),
  #"Replaced value 10" = Table.ReplaceValue(#"Replaced value 9", "", "blank", Replacer.ReplaceValue, {"Precipitation"}),
  #"Replaced value 11" = Table.ReplaceValue(#"Replaced value 10", "", "blank", Replacer.ReplaceValue, {"Damage Level"}),
  #"Replaced value 12" = Table.ReplaceValue(#"Replaced value 11", "", "blank", Replacer.ReplaceValue, {"Effect on Flight"}),
  #"Merged queries" = Table.NestedJoin(#"Replaced value 12", {"EMA", "EMO"}, #"Engine Codes Info", {"Manufacturer Code", "Model Code"}, "Engine Codes Info", JoinKind.LeftOuter),
  #"Expanded Engine Codes Info" = Table.ExpandTableColumn(#"Merged queries", "Engine Codes Info", {"Engine Codes Info Key"}, {"Engine Codes Info Key"}),
  #"Replaced value 13" = Table.ReplaceValue(#"Expanded Engine Codes Info", null, 165, Replacer.ReplaceValue, {"Engine Codes Info Key"})
in
  #"Replaced value 13"
